import type { Metadata } from "next";
import { Sora } from "next/font/google";
import Header from "@/components/home/navbar";
import About from "@/components/home/about";
import Contact from "@/components/home/contact";
import Footer from "@/components/home/footer";
const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>
      <body className={sora.className}>
        <Header />
        {children}
        <About />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
