// import React from "react";
// import Image from "next/image";
// import bgimage from "@/public/images/Section-3-Background.jpg";
// import phone from "@/public/images/Phone-932x1024.png";

// export default function TradingBot() {
//   return (
//     <>
//       <div
//         className="h-[1500px] lg:h-[1250px] flex flex-col items-start justify-start relative bg-none xl:bg-cover bg-local bg-center"
//         style={{ backgroundImage: `url(${bgimage.src})` }}
//       >
//         <div className="flex flex-col w-full  lg:flex-row xl:pl-40 mt-20 h-fit">
//           <div className="flex justify-center lg:justify-end items-center w-full lg:w-1/2 ">
//             <Image
//               src={phone}
//               alt="phone"
//               className="index-10 w-[800px] h-[800px] xl:w-[600px] xl:h-[600px]"
//             />
//           </div>

//           <div className="w-full lg:w-1/2 px-4 xl:mr-32 flex flex-col justify-center space-y-12">
//             <div className="text-[#2A364C] px-4 leading-normal text-4xl font-semibold">
//               Finally, A Crypto Trading
//               <br className="hidden lg:block" /> Bot Made For Regular,
//               <br className="hidden lg:block" />
//               <span className="py-2 px-2 rounded-lg text-white bg-[#2A364C]">
//                 Non-Techie
//               </span>
//               &nbsp;People!
//             </div>

//             <p className="leading-6 px-4 font-normal lg:font-light text-base lg:text-sm tracking-wide">
//               There are many crypto trading bots out there. However, they
//               <br className="hidden lg:block" /> are made for experienced
//               traders and/or tech-savvy people.
//               <br className="hidden lg:block" />
//               So, even though they are supposed to make trading easier, the
//               <br className="hidden lg:block" /> truth is, they are very
//               complicated.
//             </p>

//             <div className="leading-6 px-4 font-semibold text-xl tracking-wide">
//               That’s why we made EazyBot; to make crypto
//               <br className="hidden lg:block" /> trading easy and accessible to
//               everyone.
//             </div>

//             <div className="flex justify-center items-center">
//               <button className="text-white leading-6 font-base bg-hcolor text-sm tracking-wide w-full md:w-fit px-12 py-3 rounded-full shadow-2xl shadow-hcolor">
//                 Learn more
//               </button>
//             </div>
//           </div>
//         </div>

//         <TradingBotB />
//       </div>
//     </>
//   );
// }

// const TradingBotB = () => {
//   return (
//     <div className="flex justify-center items-center mt-10 px-4 xl:px-48 w-full">
//       <div className="flex flex-row justify-center items-center w-full space-x-10">
//         <div className="flex flex-col space-y-10 w-full lg:w-1/2 ">
//           <div className="text-4xl font-semibold leading-normal">
//             Fast-track your crypto
//             <br className="hidden lg:block" /> success
//           </div>

//           <div className="w-full h-auto lg:hidden justify-center items-center">
//             <div className="relative w-full h-0 pb-[56.25%]">
//               <div
//                 className="w-50 absolute inset-0 h-50 bg-cover bg-center rounded-lg z-0"
//                 style={{
//                   backgroundImage:
//                     "url('https://i.vimeocdn.com/video/1444088858-994565a96c9851f5ce7a7fa8dec3040d3bcd7a5a7fdc307758652ceac9b1f993-d?mw=800&mh=449&q=70')",
//                 }}
//               ></div>
//               <video
//                 className="inset-0 absolute w-full h-full rounded-lg object-cover z-10"
//                 controls
//                 preload="none"
//                 src="blob:https://player.vimeo.com/4aea621e-8d1e-4223-b90a-1b9e6f1bbce0"
//               >
//                 <track
//                   kind="captions"
//                   src="/texttrack/21750513.vtt?token=66c70e95_0x7c10a6bb3d11db8079340ddc53dc86b7b33f1f08"
//                   srcLang="en-x-autogenerated"
//                   label="English (auto-generated)"
//                 />
//               </video>
//             </div>
//           </div>

//           <div className="leading-6 font-light text-sm tracking-wide ">
//             Watch This Video & See For Yourself Why EazyBot Is
//             <br className="hidden lg:block" />
//             Hands-Down The Easiest & Painless Way To Trade Crypto
//           </div>
//           <div className="flex justify-center lg:justify-start items-center">
//             <button className="text-white leading-6 font-base bg-hcolor text-sm tracking-wide px-12 py-3 rounded-full shadow-2xl shadow-hcolor">
//               Learn more
//             </button>
//           </div>
//         </div>

//         <div className="w-full hidden relative lg:w-1/2 lg:flex justify-center items-center">
//           <div className="relative w-full h-0 pb-[56.25%]">
//             <div
//               className="w-50 absolute inset-0 h-50 bg-cover bg-center rounded-lg z-0"
//               style={{
//                 backgroundImage:
//                   "url('https://i.vimeocdn.com/video/1444088858-994565a96c9851f5ce7a7fa8dec3040d3bcd7a5a7fdc307758652ceac9b1f993-d?mw=800&mh=449&q=70')",
//               }}
//             ></div>
//             <video
//               className="inset-0 absolute w-full h-full rounded-lg object-cover z-10"
//               controls
//               preload="none"
//               src="blob:https://player.vimeo.com/4aea621e-8d1e-4223-b90a-1b9e6f1bbce0"
//             >
//               <track
//                 kind="captions"
//                 src="/texttrack/21750513.vtt?token=66c70e95_0x7c10a6bb3d11db8079340ddc53dc86b7b33f1f08"
//                 srcLang="en-x-autogenerated"
//                 label="English (auto-generated)"
//               />
//             </video>
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// };

import React from "react";
import Image from "next/image";
import bgimage from "@/public/images/Section-3-Background.jpg";
import phone from "@/public/images/Phone-932x1024.png";

export default function TradingBot() {
  return (
    // <div
    //   className="h-auto min-h-[1500px] lg:min-h-[1250px] flex flex-col items-start justify-start bg-none xl:bg-cover bg-local bg-center relative overflow-hidden"
    //   style={{ backgroundImage: `url(${bgimage.src})` }}
    // >
    //   <div className="flex flex-col w-full  lg:flex-row xl:pl-40 mt-20 h-fit max-w-[100vw]">
    //     <div className="flex justify-center lg:justify-end items-center w-full lg:w-1/2 ">
    //       <Image
    //         src={phone}
    //         alt="phone"
    //         className="index-10 max-w-full max-h-full w-[90%] h-auto xl:w-[600px] xl:h-[600px]"
    //       />
    //     </div>

    //     <div className="w-full lg:w-1/2 px-4 xl:mr-32 pl-0 flex flex-col justify-center space-y-6">
    //       <div className="text-[#2A364C] px-2 lg:px-4 leading-loose text-2xl lg:text-4xl font-semibold">
    //         Finally, A Crypto Trading
    //         <br className="hidden lg:block" /> Bot Made For Regular,
    //         <br className="hidden lg:block" />
    //         <span className="py-1 lg:py-2 px-2 rounded-lg text-white bg-[#2A364C]">
    //           Non-Techie
    //         </span>
    //         &nbsp;People!
    //       </div>

    //       <p className="leading-6 px-2 lg:px-4 font-normal lg:font-light text-base lg:text-sm tracking-wide">
    //         There are many crypto trading bots out there. However, they
    //         <br className="hidden lg:block" /> are made for experienced traders
    //         and/or tech-savvy people.
    //         <br className="hidden lg:block" />
    //         So, even though they are supposed to make trading easier, the
    //         <br className="hidden lg:block" /> truth is, they are very
    //         complicated.
    //       </p>

    //       <div className="leading-6 px-2 lg:px-4 font-semibold text-xl tracking-wide">
    //         That’s why we made EazyBot; to make crypto
    //         <br className="hidden lg:block" /> trading easy and accessible to
    //         everyone.
    //       </div>

    //       <div className="flex justify-center items-center ">
    //         <button className="text-white leading-6 font-base bg-hcolor text-sm tracking-wide w-full md:w-fit px-12 py-3 rounded-full shadow-2xl">
    //           Learn more
    //         </button>
    //       </div>
    //     </div>
    //   </div>

    //   <TradingBotB />
    // </div>
    <div
      className="h-auto min-h-[1500px] lg:min-h-[1250px] flex flex-col items-start justify-start gap"
      style={{ backgroundImage: `url(${bgimage.src})` }}
    >
      <div className="flex flex-col w-full lg:flex-row lg:justify-end mt-20 min-h-full max-w-[100vw] gap">
        <div className="flex justify-center lg:justify-end items-center w-full lg:w-1/2 gap">
          <Image
            src={phone}
            alt="phone"
            className="index-10 max-w-full h-fit w-[90%] xl:w-[600px] xl:h-[700px]"
          />
        </div>

        <div className="w-full lg:w-1/2 px-4 xl:mr-20 pl-0 flex flex-col justify-center space-y-6 gap">
          <div className="text-[#2A364C] px-2 lg:px-4 leading-loose text-2xl lg:text-4xl font-semibold">
            At last, a crypto trading
            <br className="hidden lg:block" /> bot designed for everyday,
            <br className="hidden lg:block" />
            <span className="py-1 lg:py-2 px-2 rounded-lg text-white  bg-blue-600">
              non-techie
            </span>
            &nbsp;People!
          </div>

          <p className="leading-6 px-2 lg:px-4 font-normal lg:font-light text-base lg:text-sm tracking-wide">
            Most crypto trading bots are built for seasoned traders and
            <br className="hidden lg:block" /> tech-savvy users. simplify
            trading, they often end up being overly complicated.
            <br className="hidden lg:block" />
          </p>

          <div className="leading-6 px-2 lg:px-4 font-semibold text-xl tracking-wide">
            We built EazyBot to make crypto trading simple and accessible for
            everyone.
            <br className="hidden lg:block" /> Now, anyone can trade with ease.
          </div>

          <div className="flex justify-center items-center ">
            <button className="text-white leading-6 font-base  bg-blue-600 text-sm tracking-wide w-full md:w-fit px-12 py-3 rounded-full shadow-2xl">
              Learn more
            </button>
          </div>
        </div>
      </div>

      <TradingBotB />
    </div>
  );
}

const TradingBotB = () => {
  return (
    <div className="flex justify-center items-center mt-10 px-4 xl:px-48 w-full overflow-hidden">
      <div className="flex flex-col lg:flex-row justify-center items-center w-full space-x-0 lg:space-x-10">
        {/* Left Side */}
        <div className="flex flex-col space-y-10 w-full lg:w-1/2  p-4">
          <div className="text-2xl lg:text-4xl font-semibold leading-normal">
            Accelerate your crypto
            <br className="hidden xl:block" />{" "}
            <span className=" text-blue-600">journey</span> to success
          </div>

          {/* ----------------------------------------------------- */}
          <div className="w-full h-auto lg:hidden justify-center items-center">
            <div className="relative w-full h-0 pb-[56.25%]">
              {/* Background Image (applied to video using a wrapper) */}
              <div
                className="absolute inset-0 bg-cover bg-center rounded-lg z-0"
                style={{
                  backgroundImage:
                    "url('https://i.vimeocdn.com/video/1444088858-994565a96c9851f5ce7a7fa8dec3040d3bcd7a5a7fdc307758652ceac9b1f993-d?mw=800&mh=449&q=70')",
                }}
              ></div>
              {/* Video */}
              <video
                className="absolute inset-0 w-full h-full rounded-lg object-cover z-10"
                controls
                preload="none"
                src="blob:https://player.vimeo.com/4aea621e-8d1e-4223-b90a-1b9e6f1bbce0"
              >
                <track
                  kind="captions"
                  src="/texttrack/21750513.vtt?token=66c70e95_0x7c10a6bb3d11db8079340ddc53dc86b7b33f1f08"
                  srcLang="en-x-autogenerated"
                  label="English (auto-generated)"
                />
              </video>
            </div>
          </div>
          {/* ----------------------------------------------------- */}
          <div className="leading-6 font-light text-sm tracking-wide">
            Watch this video and discover why EazyBot is
            <br className="hidden lg:block" />
            the simplest and most hassle-free way to trade crypto.
          </div>

          <div className="flex justify-center lg:justify-start items-center">
            <button className="text-white   bg-blue-600 text-sm tracking-wide px-8 lg:px-12 py-2 lg:py-3 rounded-full shadow-2xl">
              Learn more
            </button>
          </div>
        </div>

        {/* Right Side - Video with Background */}
        <div className="hidden lg:flex w-[1000px] relative justify-center items-center">
          <div className="relative w-full h-0 pb-[56.25%]">
            {/* Background Image (applied to video using a wrapper) */}
            <div
              className="absolute inset-0 bg-cover bg-center rounded-lg z-0"
              style={{
                backgroundImage:
                  "url('https://i.vimeocdn.com/video/1444088858-994565a96c9851f5ce7a7fa8dec3040d3bcd7a5a7fdc307758652ceac9b1f993-d?mw=800&mh=449&q=70')",
              }}
            ></div>
            {/* Video */}
            <video
              className="absolute inset-0 w-full h-full rounded-lg object-cover z-10"
              controls
              preload="none"
              src="blob:https://player.vimeo.com/4aea621e-8d1e-4223-b90a-1b9e6f1bbce0"
            >
              <track
                kind="captions"
                src="/texttrack/21750513.vtt?token=66c70e95_0x7c10a6bb3d11db8079340ddc53dc86b7b33f1f08"
                srcLang="en-x-autogenerated"
                label="English (auto-generated)"
              />
            </video>
          </div>
        </div>
      </div>
    </div>
  );
};
